### ISSUE TITLE
code is wrong

### ISSUE THREAD

**Issue by jHAX7** [mrmojololo/blooket-admin-hack#15]
i think this is a troll the code is useless and can't give you any tokens if you actually want infinite tokens i have a folder all about it in my repository.

**Comment by Blooper-glooper** [comment]
> i think this is a troll the code is useless and can't give you any tokens if you actually want infinite tokens i have a folder all about it in my repository. 

Yours itself is still in beta so there is no way in theory to get infinite unless you like work at blooket

**Comment by Wilsonboi7466** [comment]
Dude stop self-promoting it's not worth it

**Comment by mrmojololo** [comment]
stop self promoting lmao
