### ISSUE TITLE
how does this even work

### ISSUE THREAD

**Issue by slickskillzzz** [mrmojololo/blooket-admin-hack#3]

**Comment by mrmojololo** [comment]
just run the script by typing into the search bar
javascript:the script here

**Comment by slickskillzzz** [comment]
> just run the script by typing into the search bar javascript:the script here

oh sorry i didnt see the part where you said everything is in one script

**Comment by slickskillzzz** [comment]
> just run the script by typing into the search bar javascript:the script here

and ye ik how to use javascript
