### ISSUE TITLE
I GOT BANNED WTF

### ISSUE THREAD

**Issue by VillainsRule4000** [mrmojololo/blooket-admin-hack#4]
I GOT BANNED FROM BLOOKET FOR USING THIS!!! I REPORTED YOU!!!

**Comment by mrmojololo** [comment]
coping
![image](https://user-images.githubusercontent.com/73600819/173152440-38536609-07a7-472b-b4d2-5c1b8f7c831a.png)

**Comment by VillainsRule4000** [comment]
Stop editing my comments.
